[workspace]
members = ["bin/host", "bin/input-gen", "bin/input-gen-ethrex", "crates/*", "tests"]
exclude = []
resolver = "2"

[workspace.package]
version = "0.9.0"
edition = "2021"

[workspace.dependencies]
guest-common = { path = "crates/guest-common" }
guest-ethrex = { path = "crates/guest-ethrex" }
guest-reth = { path = "crates/guest-reth" }
input = { path = "crates/input" }

zisk-sdk = { git = "https://github.com/0xPolygonHermez/zisk.git", tag = "v0.18.0" }
zkvm-interface = { git = "https://github.com/0xPolygonHermez/zisk.git", tag = "v0.18.0" }
# local dev
# zisk-sdk = { path = "../zisk/sdk" }
# zkvm-interface = { path = "../zisk/zkvm-interface" }

revm = { version = "34.0.0", default-features = false }

# types (for reth)
alloy-primitives = { version = "1.5.6", default-features = false }
alloy = "1.7.3"
alloy-consensus = { version = "1.7.3", default-features = false }
alloy-json-rpc = "1.7.3"
alloy-provider = "1.7.3"
alloy-rpc-client = "1.7.3"
alloy-transport = "1.7.3"
alloy-genesis = { version = "1.7.3", default-features = false }
alloy-eips = "1.7.3"
alloy-rpc-types-eth = "1.7.3"
alloy-rpc-types-debug = { version = "1.7.3", default-features = false }

# reth
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.11.0", default-features = false }
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.11.0", default-features = false }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.11.0", default-features = false }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.11.0", default-features = false }
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.11.0" }
stateless-reth = { git = "https://github.com/paradigmxyz/stateless", rev = "ed189a51931e8589102f3139d48fdbb3bbe4c1f7", package = "stateless", default-features = false }
stateless-reth-tries = { git = "https://github.com/paradigmxyz/stateless", rev = "ed189a51931e8589102f3139d48fdbb3bbe4c1f7", package = "tries", default-features = false }

# types (for ethrex)
primitive-types = "0.13.1"
ethereum-types = "0.15.1"

# ethrex
ethrex-config = { git = "https://github.com/lambdaclass/ethrex.git", rev = "283ae1a561f46daacac99e281126901e5208b969" }
ethrex-common = { git = "https://github.com/lambdaclass/ethrex.git", rev = "283ae1a561f46daacac99e281126901e5208b969", default-features = false }
ethrex-rpc = { git = "https://github.com/lambdaclass/ethrex.git", rev = "283ae1a561f46daacac99e281126901e5208b969" }
ethrex-crypto = { git = "https://github.com/lambdaclass/ethrex.git", rev = "283ae1a561f46daacac99e281126901e5208b969", default-features = false }
stateless-ethrex = { git = "https://github.com/lambdaclass/ethrex.git", rev = "283ae1a561f46daacac99e281126901e5208b969", default-features = false, package = "ethrex-guest-program" }

# eth-act
witness-generator = { git = "https://github.com/eth-act/zkevm-benchmark-workload.git", rev = "63da9dde9b284dc4845cf7128c3f0d7c53d21654" }

# common dependencies
anyhow = { version = "1.0", default-features = false }
async-trait = "0.1"
bincode = { version = "2.0", default-features = false, features = ["serde", "std"] }
clap = { version = "4.5.7", features = ["derive", "env"] }
dotenv = "0.15.0"
eyre = "0.6.12"
k256 = { version = "0.13.4", default-features = false }
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
rayon = "1.11.0"
serde = { version = "1.0", default-features = false }
serde_with = { version = "3.14", default-features = false }
serde_json = "1.0"
tokio = { version = "1.21", default-features = false, features = [
    "rt",
    "rt-multi-thread",
] }
tokio-util = { version = "0.7", features = ["rt"] }
url = "2.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walkdir = "2"
jsonrpsee = { version = "0.26", features = ["http-client"] }
http = "1.4.0"
tempfile = "3"
rkyv = { version = "0.8.10", features = ["std", "unaligned"] }

[patch."https://github.com/paradigmxyz/stateless.git"]
stateless = { git = "https://github.com/0xPolygonHermez/zisk-patch-stateless.git", branch = "zisk/ed189a5" }
tries = { git = "https://github.com/0xPolygonHermez/zisk-patch-stateless.git", branch = "zisk/ed189a5" }
# stateless = { path = "../zisk-patch-stateless/crates/stateless" }
# tries = { path = "../zisk-patch-stateless/crates/tries" }
