[package]
name = "input"
description = ""
version.workspace = true
edition.workspace = true

[dependencies]
guest-reth.workspace = true

async-trait.workspace = true
anyhow = { workspace = true, features = ["std"] }
bincode.workspace = true
rayon.workspace = true
tracing.workspace = true
serde = { workspace = true, features = ["std", "derive"] }
serde_with = { workspace = true, features = ["std", "macros"] }

alloy-genesis = { workspace = true, features = ["std"] }
alloy-provider = { workspace = true, features = ["debug-api"] }
alloy-rpc-types-eth.workspace = true
alloy-rpc-types-debug = { workspace = true, features = ["std"] }

reth-chainspec = { workspace = true, features = ["std"] }

stateless-reth = { workspace = true, features = ["std"] }
